apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: klat3q9i9-python 
  janus-idp.io/tekton: klat3q9i9-python
  backstage.io/kubernetes-id: klat3q9i9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: klat3q9i9-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  